var StyleSheet = require('StyleSheet');

module.exports = StyleSheet.create({
  aboutMerchant: {
    height: 40,
    justifyContent: 'center',
    backgroundColor: '#fbfbfb',
    flex: 1,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
  },
  aboutMerchantText: {
    fontSize: 15,
    marginLeft: 10,
    marginTop: 10,
    color: '#bcbec0',
  },
  accountRow: {
    height: 45,
    backgroundColor: '#fff',
    borderBottomWidth: 0.25,
    borderBottomColor: '#fff',
    justifyContent: 'center',

  },
  accountText: {
    fontSize: 14,
    textAlign: 'left',
    fontWeight: '400',
    paddingLeft: 10,
    color: '#fff',
  },
  amount: {
    flex: 4,
    textAlign: 'right',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 6,
    marginRight: 10,
    color: '#45d695',
    alignItems: 'stretch'
  },
  balance: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#313838',
  },
  balanceSign: {
    marginTop: 1.35,
    marginRight: 3,
    fontSize: 18,
    color: '#313838',
  },
  balanceView: {
    flex: 1,
    justifyContent: 'center',
    flexDirection: 'row',
    paddingRight: 50,
  },
  bankImage: {
    height: 90,
    marginTop: 10,
  },
  cash: {
    width: 91.5,
    margin: 14,
    borderWidth: 1,
    borderColor: '#45d695',
    borderRadius: 2,
    flexDirection: 'row',
  },
  container: {
    flex: 1,
    backgroundColor: '#fbfbfb'
  },
  container2: {
    flex: 1,
    backgroundColor: '#fbfbfb'
  },
  container3: {
    flex: 1,
    backgroundColor: '#FFFFFF'
  },
  currentOffer: {
    fontSize: 18,
    textAlign: 'left',
    fontWeight: 'bold',
    paddingLeft: 10,
    color: '#313838',
  },
  dollarSign: {
    flex: 1,
    textAlign: 'left',
    fontSize: 18,
    marginTop: 6,
    marginLeft: 10,
    color: '#45d695',
  },
  greyendivider: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
  },
  header: {
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'left',
    paddingLeft: 10,
    marginTop: 10,
    color: '#1C2D3A',
  },
  icon: {
    marginLeft: 10,
    marginRight: 10,
  },
  icon2: {
    marginLeft: 10,
    marginRight: 10,
  },
  icon3: {
    marginLeft: 10,
    marginRight: 20,
  },
  instructions: {
    fontSize: 15,
    textAlign: 'left',
    paddingLeft: 10,
    color: '#bcbec0',
  },
  loginBarButton:{
    width: 50,
    height: 45,
    paddingRight: 10,
    paddingTop: 14,
    fontSize: 15,
    color: '#45d695'
  },
  navBar: {
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fbfbfb',
  },
  navBarText: {
    color: '#313838',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
  },
  navBarText2: {
    color: '#313838',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
    marginLeft: 30,
  },
  map: {
    height: 200,
  },
  mapSpinner: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#fff'
  },
  MFAQuestion: {
    flex: 1,
    fontSize: 15,
    fontWeight: 'bold',
    backgroundColor: '#fff',
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  MFAQuestionWrapper: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    flex: 1,
    flexDirection: 'column',
  },
  row: {
    height: 64,
    backgroundColor: '#fff',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
    flexDirection: 'row',
  },
  row2: {
    height: 64,
    backgroundColor: '#fff',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
    borderTopWidth: 1,
    borderTopColor: '#E9E8EA',
    flexDirection: 'row',
  },
  row3: {
    height: 64,
    backgroundColor: '#fff',
    flexDirection: 'row',
  },
  page: {
    flex: 1,
  },
  percentageTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 300,
    backgroundColor: '#fff',
  },
  percentageTopNumber: {
    fontSize: 48,
    fontWeight: '500',
  },
  percentageTopSign: {
    marginLeft: 5,
    fontSize: 48,
    fontWeight: '200',
  },
  place: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  placeBox: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    padding: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
  },
  placeBoxTitle: {
    color: '#313838',
    fontSize: 18,
    fontWeight: 'bold',
  },
  placeBoxInfo: {
    color: '#bcbec0',
    fontSize: 15,
  },
  placeName: {
    fontSize: 19,
    fontWeight: 'bold',
    textAlign: 'left',
    paddingLeft: 10,
    color: '#313838',
  },
  placeInformationRow: {
    height: 45,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
    backgroundColor: '#fff'
  },
  placeInformationDetailRow: {
    height: 45,
    backgroundColor: '#fff',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
    justifyContent: 'center',
  },
  placeInformationClaimButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#45d695',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
    marginRight: 10,
    marginLeft: 10,
    borderRadius: 2,
  },
  placeInformationClaimButtonWrapper: {
    height: 65,
    backgroundColor: '#fff',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
  },
  placeInformationClaimButtonText:{
    fontSize: 18,
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#45d695',
  },
  placeInformationRowLeft:{
    fontSize: 14,
    textAlign: 'left',
    paddingLeft: 10,
    color: '#45d695',
  },
  placeInformationRowRight: {
    fontSize: 14,
    textAlign: 'right',
    fontWeight: 'bold',
    paddingRight: 10,
    color: '#313838',
  },
  percent: {
    width: 91.5,
    margin: 14,
    backgroundColor: '#45d695',
    borderRadius: 2,
    flexDirection: 'row',
  },
  percentNumber: {
    flex: 2,
    textAlign: 'left',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 6,
    marginLeft: 10,
    color: '#fff',
    alignItems: 'stretch'
  },
  percentSign: {
    flex: 1,
    textAlign: 'right',
    fontSize: 18,
    marginTop: 7,
    marginRight: 10,
    color: '#fff',
  },
  signUpLanding: {
    backgroundColor: '#fbfbfb',
  },
  signUpInfo: {
    paddingTop: 15,
    paddingLeft: 10,
    paddingRight: 10,
    fontWeight: 'bold',
    fontSize: 12,
    color: '#bcbec0',
    backgroundColor: '#fff',
    textAlign: 'center',
  },
  signUpTextView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#fff'

  },
  signUpTextOr: {
    marginTop: 2,
    marginBottom: 12,
  },
  signUpText: {
    color: '#45d695',
    marginTop: 2,
    marginBottom: 12,
  },
  signUpTextField: {
    flex: 1,
    backgroundColor: '#fff',
    paddingLeft: 10,
    borderWidth: 0.25,
    borderColor: '#bcbec0',
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 2,
  },
  signUpTextFieldWrapper: {
    height: 55,
    backgroundColor: '#fff',
  },
  signUpButtonWrapper: {
    height: 55,
    backgroundColor: '#fff',
  },
  signUpButtonButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#45d695',
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginRight: 10,
    marginLeft: 10,
    borderRadius: 2,
  },
  signUpOr: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    paddingLeft: 10,
    paddingRight: 10,
  },
  signUpOrText: {
    paddingTop: 10,
    paddingLeft: 10,
    paddingRight: 10,
    fontWeight: 'bold',
    fontSize: 12,
    color: '#bcbec0',
    backgroundColor: '#fff',
    textAlign: 'center',
  },
  signUpOrDivider: {
    flex: 1,
    height: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
  },
  space: {
    flexDirection: 'row',
    height: 45,
    backgroundColor: '#fbfbfb',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
  },
  space2: {
    justifyContent: 'center',
    height: 40,
    backgroundColor: '#fff',
    borderBottomWidth: 0.25,
    borderBottomColor: '#1C2D3A'
  },
  spacer: {
    flex: 1,
    height: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 0.5,
    borderBottomColor: '#E9E8EA',
  },
  scrollviewwrapper: {
    flex: 1,
    backgroundColor: '#fbfbfb',
  },
  topBar:{
    marginTop: 24,
  },
  topBar2:{
    height: 24,
    backgroundColor: '#fbfbfb',
  },
});
